spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: backend-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/academic-years/**,/api/v1/classes/**,/api/v1/departments/**,/api/v1/semesters/**,/api/v1/subjects/**,/api/v1/teachers/**,/api/v1/teacher-subjects/**,/api/v1/homeroom-teachers/**
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**
        - id: student-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/students/**,/api/v1/enrollments/**
        - id: schedule-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/schedules/**,/api/v1/events/**
        - id: attendance-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/attendance/**
        - id: assignment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/assignment/**
        - id: grade-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/grade/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, routes

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
